settings.experimental = true

[tools]
go = "1.23.2"
watchexec = "1.25.1"

[tasks."example:qm"]
description = "Run the example in query-mutations"
run = "go run ./examples/query-mutations/main.go"
sources = [
  "generator/**/*.go",
  "internal/**/*.go",
  "./examples/query-mutations/main.go",
]

[tasks."example:simple"]
description = "Run the example in simple"
run = "go run ."
dir = "./examples/simple"
